import { MatchupSchema, SupabaseParlay } from "./Interfaces";

export const demoParlays: SupabaseParlay[] = [
  {
    user_id: "c967b5a2-479d-5b20-9c58-27e164630d33",
    parlay_id: "67",
    frontend_is_active: false,
    is_active: true,
    is_winner: false,
    legs: [
      {
        matchup_id: 0,
        day_id: 6,
        parlay_id: "temp",
        frontend_id: "JASON-SPREAD BETTING",
        odds: -150,
        team: "JASON",
        text: "+100.5",
      },
    ],
    payout: 16.67,
    created_at: new Date(1762659052276).toUTCString(),
    total_odds: -150,
    wager: 10,
    matchup_id: 4,
    expires_at: new Date(1762659052276).toUTCString(),
  },
  {
    user_id: "c967b5a2-479d-5b20-9c58-27e164630d33",
    parlay_id: "5555",
    matchup_id: 4,
    total_odds: 596,
    payout: 139.16,
    wager: 20,
    frontend_is_active: false,
    is_winner: false,
    is_active: true,
    legs: [
      {
        frontend_id: "Amen's Shampoo/SPREAD BETTING",
        team: "Amen's Shampoo",
        matchup_id: 0,
        day_id: 6,
        parlay_id: "temp",
        text: "+141.5",
        odds: -110,
      },
      {
        frontend_id: "Amen's Shampoo v Ion Run It/U/TOTAL POINTS",
        team: "Amen's Shampoo v Ion Run It",
        matchup_id: 0,
        day_id: 6,
        parlay_id: "temp",
        text: "O 2821.5",
        odds: -110,
      },
      {
        frontend_id: "Kane Train 🚂/MONEYLINE",
        team: "Kane Train 🚂",
        matchup_id: 0,
        day_id: 6,
        parlay_id: "temp",
        text: "",
        odds: -110,
      },
    ],
    created_at: new Date(1762973845208).toUTCString(),
    expires_at: new Date(1763417915502).toUTCString(),
  },
];

export const demoWeeklySlate: MatchupSchema[] = [
  {
    road: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Professor Coach's Pupils",
      record: "1-2",
      team_total: { text: "2000.5", over_odds: -110, under_odds: -110 },
      spread: { live_value: "200.5", text: "+70.5", odds: -110 },
      points: { live_value: "3000", text: "O 3985.5", odds: -150 },
      moneyline: { live_value: "2300-2200", text: "", odds: 200 },
      live_score: 1352.8,
      top_5: [
        {
          name: "Scottie Barnes",
          live_total: 140,
          team: "TOR",
          last_game: "",
          status: "ACTIVE",
          average: 58.8,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Alex Sarr",
          live_total: 5,
          team: "WAS",
          last_game: "",
          status: "ACTIVE",
          average: 53.59,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Pascal Siakam",
          live_total: 7,
          team: "IND",
          last_game: "",
          status: "ACTIVE",
          average: 52.63,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Evan Mobley",
          live_total: 5,
          team: "CLE",
          last_game: "",
          status: "ACTIVE",
          average: 52.38,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Keyonte George",
          live_total: 11,
          team: "UTA",
          last_game: "",
          status: "ACTIVE",
          average: 47.78,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
      ],
    },
    home: {
      icon: "https://i.pinimg.com/236x/06/11/27/061127dd8493543cf15f06950bfd0c17.jpg",
      name: "Sacred timeline TVA",
      record: "1-2",
      team_total: { text: "1900", over_odds: -220, under_odds: -220 },
      spread: { live_value: "200.5", text: "-70.5", odds: -110 },
      points: { live_value: "3000", text: "U 3985.5", odds: 125 },
      moneyline: { live_value: "2300-2200", text: "", odds: -120 },
      live_score: 1449.85,
      top_5: [
        {
          name: "Shai Gilgeous-Alexander",
          live_total: 140,
          team: "OKC",
          last_game: "",
          status: "ACTIVE",
          average: 73.23,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Donovan Mitchell",
          live_total: 140,
          team: "CLE",
          last_game: "",
          status: "ACTIVE",
          average: 65.2,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Jalen Duren",
          live_total: 6,
          team: "DET",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 53.12,
          games_left: 0,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Miles Bridges",
          live_total: 6,
          team: "CHA",
          last_game: "",
          status: "ACTIVE",
          average: 51.91,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Jrue Holiday",
          live_total: 9,
          team: "POR",
          last_game: "",
          status: "ACTIVE",
          average: 50.83,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
      ],
    },
    isClose: true,
  },
  {
    road: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Mr. Send That Vid",
      record: "2-1",
      team_total: { text: "2000.5", over_odds: -110, under_odds: -110 },
      spread: { live_value: "200.5", text: "+100.5", odds: -150 },
      points: { live_value: "3000", text: "O 3785.5", odds: -120 },
      moneyline: { live_value: "2300-2200", text: "", odds: 275 },
      live_score: 1223.15,
      top_5: [
        {
          name: "Tyrese Maxey",
          live_total: 2,
          team: "PHL",
          last_game: "",
          status: "ACTIVE",
          average: 73.05,
          games_left: 0,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Josh Giddey",
          live_total: 5,
          team: "CHI",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 64.27,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Anthony Edwards",
          live_total: 16,
          team: "MIN",
          last_game: "",
          status: "ACTIVE",
          average: 55.78,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Ivica Zubac",
          live_total: 8,
          team: "LAC",
          last_game: "",
          status: "ACTIVE",
          average: 45.48,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Kon Knueppel",
          live_total: 9,
          team: "CHA",
          last_game: "",
          status: "ACTIVE",
          average: 41.12,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
      ],
    },
    home: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Ion Run It",
      record: "2-1",
      team_total: { text: "1900", over_odds: -220, under_odds: -220 },
      spread: { live_value: "200.5", text: "-100.5", odds: -110 },
      points: { live_value: "3000", text: "U 3785.5", odds: -130 },
      moneyline: { live_value: "2300-2200", text: "", odds: -120 },
      live_score: 1422.05,
      top_5: [
        {
          name: "Austin Reaves",
          live_total: 2,
          team: "LAL",
          last_game: "",
          status: "ACTIVE",
          average: 65.01,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Julius Randle",
          live_total: 2,
          team: "MIN",
          last_game: "",
          status: "ACTIVE",
          average: 62.76,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Jalen Johnson",
          live_total: 4,
          team: "ATL",
          last_game: "",
          status: "ACTIVE",
          average: 61.08,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Karl-Anthony Towns",
          live_total: 3,
          team: "NYK",
          last_game: "",
          status: "ACTIVE",
          average: 59.27,
          games_left: 0,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Norman Powell",
          live_total: 7,
          team: "MIA",
          last_game: "",
          status: "ACTIVE",
          average: 51.25,
          games_left: 0,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
      ],
    },
    isClose: false,
  },
  {
    road: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Zeke's spinal fluid",
      record: "3-0",
      team_total: { text: "2000.5", over_odds: -110, under_odds: -110 },
      spread: { live_value: "200.5", text: "+35.5", odds: -110 },
      points: { live_value: "3000", text: "O 3800.5", odds: -220 },
      moneyline: { live_value: "2300-2200", text: "", odds: 200 },
      live_score: 1617.0,
      top_5: [
        {
          name: "Nikola Jokic",
          live_total: 140,
          team: "DEN",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 95.28,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Stephen Curry",
          live_total: 7,
          team: "GSW",
          last_game: "",
          status: "ACTIVE",
          average: 59.48,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Jaylen Brown",
          live_total: 2,
          team: "BOS",
          last_game: "",
          status: "ACTIVE",
          average: 51.63,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Stephon Castle",
          live_total: 10,
          team: "SAS",
          last_game: "",
          status: "ACTIVE",
          average: 50.22,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Mikal Bridges",
          live_total: 8,
          team: "NYK",
          last_game: "",
          status: "ACTIVE",
          average: 47.99,
          games_left: 0,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
      ],
    },
    home: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Amen's Shampoo",
      record: "1-1",
      team_total: { text: "1900", over_odds: -220, under_odds: -220 },
      spread: { live_value: "200.5", text: "-35.5", odds: -150 },
      points: { live_value: "3000", text: "U 3800.5", odds: 125 },
      moneyline: { live_value: "2300-2200", text: "", odds: -185 },
      live_score: 1419.9,
      top_5: [
        {
          name: "Alperen Sengun",
          live_total: 4,
          team: "HOU",
          last_game: "",
          status: "ACTIVE",
          average: 64.31,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Deni Avdija",
          live_total: 3,
          team: "POR",
          last_game: "",
          status: "ACTIVE",
          average: 54.95,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Franz Wagner",
          live_total: 4,
          team: "ORL",
          last_game: "",
          status: "ACTIVE",
          average: 50.03,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Trey Murphy III",
          live_total: 9,
          team: "NOP",
          last_game: "",
          status: "ACTIVE",
          average: 47.88,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Nikola Vucevic",
          live_total: 10,
          team: "CHI",
          last_game: "",
          status: "ACTIVE",
          average: 46.63,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
      ],
    },
    isClose: false,
  },
  {
    road: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Haruko Warriors",
      record: "2-1",
      team_total: { text: "2000.5", over_odds: -110, under_odds: -110 },
      spread: { live_value: "200.5", text: "+35.5", odds: -110 },
      points: { live_value: "3000", text: "O 3985.5", odds: -220 },
      moneyline: { live_value: "2300-2200", text: "", odds: 200 },
      live_score: 1375.1,
      top_5: [
        {
          name: "Victor Wembanyama",
          live_total: 2,
          team: "SAS",
          last_game: "",
          status: "ACTIVE",
          average: 74.0,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Lauri Markkanen",
          live_total: 3,
          team: "UTA",
          last_game: "",
          status: "ACTIVE",
          average: 59.18,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Jalen Brunson",
          live_total: 8,
          team: "NYK",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 57.47,
          games_left: 0,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Derrick White",
          live_total: 6,
          team: "BOS",
          last_game: "",
          status: "ACTIVE",
          average: 43.34,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Aaron Gordon",
          live_total: 13,
          team: "DEN",
          last_game: "",
          status: "ACTIVE",
          average: 41.94,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
      ],
    },
    home: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Kane Train \ud83d\ude82",
      record: "1-2",
      team_total: { text: "1900", over_odds: -220, under_odds: -220 },
      spread: { live_value: "200.5", text: "-35.5", odds: -150 },
      points: { live_value: "3000", text: "U 3985.5", odds: 125 },
      moneyline: { live_value: "2300-2200", text: "", odds: -185 },
      live_score: 1699.95,
      top_5: [
        {
          name: "Cade Cunningham",
          live_total: 4,
          team: "DET",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 67.5,
          games_left: 0,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Jamal Murray",
          live_total: 14,
          team: "DEN",
          last_game: "",
          status: "ACTIVE",
          average: 53.06,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Kevin Durant",
          live_total: 8,
          team: "HOU",
          last_game: "",
          status: "ACTIVE",
          average: 49.95,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Domantas Sabonis",
          live_total: 13,
          team: "SAC",
          last_game: "",
          status: "ACTIVE",
          average: 48.93,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Ryan Rollins",
          live_total: 3,
          team: "MIL",
          last_game: "",
          status: "ACTIVE",
          average: 46.15,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
      ],
    },
    isClose: false,
  },
  {
    road: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "TUGBOBO MEDICAL CENTER",
      record: "0-4",
      team_total: { text: "2000.5", over_odds: -110, under_odds: -110 },
      spread: { live_value: "200.5", text: "+35.5", odds: -110 },
      points: { live_value: "3000", text: "O 4100.5", odds: -220 },
      moneyline: { live_value: "2300-2200", text: "", odds: 200 },
      live_score: 1388.45,
      top_5: [
        {
          name: "Luka Doncic",
          live_total: 5,
          team: "LAL",
          last_game: "",
          status: "ACTIVE",
          average: 81.87,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "James Harden",
          live_total: 6,
          team: "LAC",
          last_game: "",
          status: "ACTIVE",
          average: 65.95,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Michael Porter Jr.",
          live_total: 10,
          team: "BKN",
          last_game: "",
          status: "ACTIVE",
          average: 50.4,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Jarrett Allen",
          live_total: 17,
          team: "CLE",
          last_game: "",
          status: "ACTIVE",
          average: 41.6,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
        {
          name: "Jaden McDaniels",
          live_total: 18,
          team: "MIN",
          last_game: "",
          status: "ACTIVE",
          average: 41.28,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
      ],
    },
    home: {
      icon: "https://i.postimg.cc/P535NpGk/IMG-8105.jpg",
      name: "Mad Wrld",
      record: "0-3",
      team_total: { text: "1900", over_odds: -220, under_odds: -220 },
      spread: { live_value: "200.5", text: "-35.5", odds: -150 },
      points: { live_value: "3000", text: "U 4100.5", odds: 125 },
      moneyline: { live_value: "2300-2200", text: "", odds: -185 },
      live_score: 1234.8,
      top_5: [
        {
          name: "Giannis Antetokounmpo",
          live_total: 140,
          team: "MIL",
          last_game: "",
          status: "DAY_TO_DAY",
          average: 81.25,
          games_left: 1,
          position: "PF",
          prop_line: { text: "45.5", over_odds: 250, under_odds: -170 },
        },
        {
          name: "Devin Booker",
          live_total: 3,
          team: "PHO",
          last_game: "",
          status: "ACTIVE",
          average: 59.3,
          games_left: 1,
          position: "PG",
          prop_line: { text: "150.5", over_odds: 300, under_odds: 125 },
        },
        {
          name: "Jimmy Butler III",
          live_total: 5,
          team: "GSW",
          last_game: "",
          status: "ACTIVE",
          average: 48.79,
          games_left: 1,
          position: "SF",
          prop_line: { text: "100.5", over_odds: -110, under_odds: -110 },
        },
        {
          name: "Kyshawn George",
          live_total: 13,
          team: "WAS",
          last_game: "",
          status: "ACTIVE",
          average: 41.43,
          games_left: 1,
          position: "SG",
          prop_line: { text: "130.5", over_odds: 125, under_odds: -250 },
        },
        {
          name: "Onyeka Okongwu",
          live_total: 9,
          team: "ATL",
          last_game: "",
          status: "ACTIVE",
          average: 41.29,
          games_left: 1,
          position: "C",
          prop_line: { text: "140.5", over_odds: -110, under_odds: -104 },
        },
      ],
    },
    isClose: true,
  },
];

export const progressBarWidth: Map<string, string> = new Map([
  [
    "0",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-2/100",
  ],
  [
    "1",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-2/100",
  ],
  [
    "2",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-2/100",
  ],
  [
    "3",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-3/100",
  ],
  [
    "4",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-4/100",
  ],
  [
    "5",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-5/100",
  ],
  [
    "6",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-6/100",
  ],
  [
    "7",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-7/100",
  ],
  [
    "8",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-8/100",
  ],
  [
    "9",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-9/100",
  ],
  [
    "10",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-10/100",
  ],
  [
    "11",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-11/100",
  ],
  [
    "12",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-12/100",
  ],
  [
    "13",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-13/100",
  ],
  [
    "14",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-14/100",
  ],
  [
    "15",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-15/100",
  ],
  [
    "16",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-16/100",
  ],
  [
    "17",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-17/100",
  ],
  [
    "18",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-18/100",
  ],
  [
    "19",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-19/100",
  ],
  [
    "20",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-20/100",
  ],
  [
    "21",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-21/100",
  ],
  [
    "22",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-22/100",
  ],
  [
    "23",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-23/100",
  ],
  [
    "24",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-24/100",
  ],
  [
    "25",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-25/100",
  ],
  [
    "26",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-26/100",
  ],
  [
    "27",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-27/100",
  ],
  [
    "28",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-28/100",
  ],
  [
    "29",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-29/100",
  ],
  [
    "30",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-30/100",
  ],
  [
    "31",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-31/100",
  ],
  [
    "32",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-32/100",
  ],
  [
    "33",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-33/100",
  ],
  [
    "34",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-34/100",
  ],
  [
    "35",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-35/100",
  ],
  [
    "36",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-36/100",
  ],
  [
    "37",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-37/100",
  ],
  [
    "38",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-38/100",
  ],
  [
    "39",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-39/100",
  ],
  [
    "40",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-40/100",
  ],
  [
    "41",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-41/100",
  ],
  [
    "42",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-42/100",
  ],
  [
    "43",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-43/100",
  ],
  [
    "44",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-44/100",
  ],
  [
    "45",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-45/100",
  ],
  [
    "46",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-46/100",
  ],
  [
    "47",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-47/100",
  ],
  [
    "48",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-48/100",
  ],
  [
    "49",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-49/100",
  ],
  [
    "50",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-50/100",
  ],
  [
    "51",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-51/100",
  ],
  [
    "52",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-52/100",
  ],
  [
    "53",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-53/100",
  ],
  [
    "54",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-54/100",
  ],
  [
    "55",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-55/100",
  ],
  [
    "56",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-56/100",
  ],
  [
    "57",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-57/100",
  ],
  [
    "58",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-58/100",
  ],
  [
    "59",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-59/100",
  ],
  [
    "60",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-60/100",
  ],
  [
    "61",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-61/100",
  ],
  [
    "62",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-62/100",
  ],
  [
    "63",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-63/100",
  ],
  [
    "64",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-64/100",
  ],
  [
    "65",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-65/100",
  ],
  [
    "66",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-66/100",
  ],
  [
    "67",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-67/100",
  ],
  [
    "68",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-68/100",
  ],
  [
    "69",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-69/100",
  ],
  [
    "70",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-70/100",
  ],
  [
    "71",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-71/100",
  ],
  [
    "72",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-72/100",
  ],
  [
    "73",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-73/100",
  ],
  [
    "74",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-74/100",
  ],
  [
    "75",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-75/100",
  ],
  [
    "76",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-76/100",
  ],
  [
    "77",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-77/100",
  ],
  [
    "78",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-78/100",
  ],
  [
    "79",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-79/100",
  ],
  [
    "80",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-80/100",
  ],
  [
    "81",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-81/100",
  ],
  [
    "82",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-82/100",
  ],
  [
    "83",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-83/100",
  ],
  [
    "84",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-84/100",
  ],
  [
    "85",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-85/100",
  ],
  [
    "86",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-86/100",
  ],
  [
    "87",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-87/100",
  ],
  [
    "88",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-88/100",
  ],
  [
    "89",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-89/100",
  ],
  [
    "90",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-90/100",
  ],
  [
    "91",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-91/100",
  ],
  [
    "92",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-92/100",
  ],
  [
    "93",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-93/100",
  ],
  [
    "94",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-94/100",
  ],
  [
    "95",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-95/100",
  ],
  [
    "96",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-96/100",
  ],
  [
    "97",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-97/100",
  ],
  [
    "98",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-98/100",
  ],
  [
    "99",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-99/100",
  ],
  [
    "100",
    "h-[4px] z-50 bg-blue-900 bases-0 grow flex-row box-border rounded-l-md relative w-100/100",
  ],
]);

export const propField = [
  "SPREAD BETTING",
  "TOTAL POINTS",
  "MONEYLINE",
  "TEAM SCORE",
  "PLAYER SCORE",
];
